config/routes.rb
Rails.application.routes.draw do
  resources :reviews

  root "reviews#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord

    validates :title, presence:true
    validates :body, length: {minimum: 10}
    validates :score, numericality: {only_integer: true, greater_than: 0, less_than_or_equal_to:10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index 
        #show all reviews 
       @reviews = Review.all
    end


    def new
        #new review 
        @review = Review.new
    end


    def create
        #create new review with model ie: title,body, and score
        @review = Review.new(form_params)

        #save review 
        @review.save
        
        redirect_to root_path
    end


    def show
        #individual review page
        @review = Review.find(params[:id])
    end


    def destroy
        #find individual review
        @review = Review.find(params[:id])
        #destroy it
        @review.destroy
        #redirect to homepage
        redirect_to root_path

    end


    def edit
        #find individual review to edit
        @review = Review.find(params[:id])
    end

    def update
        @review = Review.find(params[:id])
        @review.update(form_params)
        redirect_to review_path
    end

   
    def form_params
        params.require(:review).permit(:title , :body, :score)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header>
    <nav>
      
      <div class="logo"><%= link_to root_path do %>
        <%= image_tag "cupcake.jpeg" %>
        <% end %>
      </div>
      </nav>
      <nav>
      <h1 class="title">One Cheat Day</h1>
      </nav>
      <nav>
      <div class="reviewPath">
        <%= link_to "Add Your Review" , new_review_path  %>
      </div>
    </nav>

    
  </header>
    <%= yield %>

    <footer>
     <p> Copyright 2023 Project Reviews </p>
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review do |f|%>
   
    <div class="reviewBody">
        
        <p class="textTitle">
            
            <%= f.label :title  %>
            <%= f.text_field :title %>
        </p>

        <p class="body">
            <%= f.label :body  %>
            <%= f.text_area :body%>
        </p>

        <p class="">
            <%= f.label :score  %>
            <%= f.number_field :score %>
        </p>
    
    
    
    <%= f.submit "Save review" %>
    </div>
<%end%>

app/views/reviews/edit.html.erb
<h3> Please edit your review<h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% @reviews.each do |index| %> 

    <div class="review">
        <%= link_to index.title, review_path(index) %>
    </div>
<% end %>

app/views/reviews/new.html.erb
<h3 class="newForm"> Thanks for visiting. We'd love to have your feedback!

<h3>


<%= render "form" %>

app/views/reviews/show.html.erb
<div class="showForm">
    <h1><%= @review.title %></h1>

    <div class="score">
        <%= @review.score %> / 10
    </div>

    <div class="body">
        <%= simple_format @review.body %> 
    </div>

    <div class ="action">
        <%= link_to "Edit this review", edit_review_path(@review) %>
    <%= button_to "Delete this review", review_path(@review), method: :delete, onclick: "return confirm ('Are you sure??')" %>

</div>